In [2]:
import pandas as pd

In [3]:
pd.__version__

'1.5.3'

In [4]:
df = pd.read_csv('laptops.csv')

In [5]:
df.head()

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

In [7]:
df.describe()

RAM      Storage       Screen  Final Price
count  2160.000000  2160.000000  2156.000000  2160.000000
mean     15.413889   596.294444    15.168112  1312.638509
std       9.867815   361.220506     1.203329   911.475417
min       4.000000     0.000000    10.100000   201.050000
25%       8.000000   256.000000    14.000000   661.082500
50%      16.000000   512.000000    15.600000  1031.945000
75%      16.000000  1000.000000    15.600000  1708.970000
max     128.000000  4000.000000    18.000000  7150.470000

In [8]:
df['Brand'].nunique()

27

In [9]:
df.isnull().sum()

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64

In [10]:
df.head()

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

In [17]:
df.dtypes

Laptop           object
Status           object
Brand            object
Model            object
CPU              object
RAM               int64
Storage           int64
Storage type     object
GPU              object
Screen          float64
Touch            object
Final Price     float64
dtype: object

In [18]:
df[df['Brand'] == 'Dell']['Final Price'].max()

3936.0

In [20]:
df['Screen'].median()

15.6

In [21]:
df['Screen'].mode()

0    15.6
Name: Screen, dtype: float64

In [22]:
df['Screen'].fillna(15.6)

0       15.6
1       15.6
2       15.6
3       15.6
4       15.6
        ... 
2155    17.3
2156    17.3
2157    17.3
2158    13.4
2159    13.4
Name: Screen, Length: 2160, dtype: float64

In [23]:
df.isnull().sum()

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64

In [24]:
df['Screen'].fillna(15.6, inplace=True)

In [25]:
df.isnull().sum()

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             0
Touch              0
Final Price        0
dtype: int64

In [26]:
df['Screen'].median()

15.6

In [32]:
df_new = df[df['Brand'] == 'Innjoo']

In [31]:
df_new.head()

Laptop Status Brand     Model  \
161  Dell Vostro 3510 Intel Core i3-1115G4/8 GB/256...    New  Dell    Vostro   
271  Dell Vostro 3510 Intel Core i5-1135G7/8 GB/256...    New  Dell    Vostro   
281  Dell Vostro 3520 Intel Core i7-1255U/16GB/512G...    New  Dell    Vostro   
319  Dell Latitude 3520 Intel Core i5-1135G7/8GB/25...    New  Dell  Latitude   
328  Dell Vostro 3510 Intel Core i5-1135G7/16 GB/51...    New  Dell    Vostro   

               CPU  RAM  Storage Storage type  GPU  Screen Touch  Final Price  
161  Intel Core i3    8      256          SSD  NaN    15.6    No       599.00  
271  Intel Core i5    8      256          SSD  NaN    15.6    No       690.15  
281  Intel Core i7   16      512          SSD  NaN    15.6    No       889.00  
319  Intel Core i5    8      256          SSD  NaN    15.6    No       789.00  
328  Intel Core i5   16      512          SSD  NaN    15.6    No       869.00

In [33]:
resultado = df[df['Brand'] == 'Innjoo'][['RAM', 'Storage', 'Screen']]

In [36]:
resultado.describe()

RAM     Storage     Screen
count  6.000000    6.000000   6.000000
mean   6.333333  192.000000  14.600000
std    1.505545  171.730021   0.774597
min    4.000000   64.000000  14.100000
25%    6.000000   80.000000  14.100000
50%    6.000000  128.000000  14.100000
75%    7.500000  224.000000  15.225000
max    8.000000  512.000000  15.600000

In [39]:
X = resultado.values

In [40]:
X

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [41]:
XTX = X.T.dot(X)

In [42]:
XTX

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

In [44]:
import numpy as np
inv = np.linalg.inv(XTX)

In [45]:
inv

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

In [46]:
y = np.array([1100, 1300, 800, 900, 1000, 1100])

In [47]:
w = inv.dot(X.T).dot(y)

In [48]:
w

array([45.58076606,  0.42783519, 45.29127938])

In [49]:
w.sum()

91.29988062995588